### ISSUE TITLE
Create a list of items / tasks before dev release

### ISSUE THREAD

**Issue by mccrodp** [RoySegall/message_ui#13]
It would be great if we can put together a list of items to fix before a dev release.

I have some here also in the fork: https://github.com/mccrodp/message_ui/issues

**Comment by RoySegall** [comment]
It's those one - https://github.com/RoySegall/message_ui/issues?q=is%3Aissue+is%3Aopen+label%3A%22Drupal+8%22

**Comment by mccrodp** [comment]
Great!
