### ISSUE TITLE
Message update arguments is running when the option is off.

### ISSUE THREAD

**Issue by nedSaf** [RoySegall/message_ui#16]
The "Update messages arguments" functionality is running regardless if it's turned on or off.
![message_settings___ _ _](https://cloud.githubusercontent.com/assets/7369740/21146169/63c91f42-c159-11e6-945b-80f0936967d0.jpg)

**Comment by nedSaf** [comment]
@RoySegall Is it deployed to drupal.org ?

**Comment by RoySegall** [comment]
Not yet. I'll deploy it now but it will be available tomorrow(at least)

**Comment by RoySegall** [comment]
Deployed to d.o

**Comment by nedSaf** [comment]
10x bro, I'll keep an eye on it.
