### ISSUE TITLE
Suggestion to make a dev release on drupal.org for Drupal 8

### ISSUE THREAD

**Issue by mccrodp** [RoySegall/message_ui#19]
Hey @RoySegall, it looks like neither of us have the time to push this over the finish line at the moment.

I suggest that we unblock this module and make it accessible on Drupal.org as it is close to being a good dev release. This will allow for a wider audience to see it, getting more traction and perhaps even more contributions.

I understand the rationale behind keeping Message module off drupal.org until it was fully stable, but it is a main module in the stack, this is a sub module which is not used as much. I feel we are just blocking people by keeping it here only. What do you think?

I have made [Message Private](https://www.drupal.org/project/message_private) available as dev release on Drupal.org even though it has Message UI as a dependency and I have called for people to help on Message UI on the project page.

**Comment by RoySegall** [comment]
I can give you commit access on d.o(as well here) if you'd like to.

**Comment by mccrodp** [comment]
Sounds good @RoySegall, thanks ✋

**Comment by mccrodp** [comment]
Thanks @RoySegall. I made a dev release now and updated the project page to call for help on closing out the stable release blockers for D8.

**Comment by RoySegall** [comment]
awesome.
