### ISSUE TITLE
Add travis CI integration

### ISSUE THREAD

**Issue by RoySegall** [RoySegall/message_ui#5]
As all the modules this module need CI integration as well.

**Comment by mccrodp** [comment]
This should come in on this PR (for D8 at least): https://github.com/RoySegall/message_ui/pull/2

**Comment by mccrodp** [comment]
This should be ok from module side, should just need to be enabled on Travis your side. [Tests still failing though on D8]

**Comment by RoySegall** [comment]
The tests did run at all... No green or red V sign near the commits. If the tests are failing we should fix them and continue with the work.

**Comment by mccrodp** [comment]
The tests were running fine for me as I had setup message_ui on my travis account, have you set up this module on your account? https://travis-ci.org/mccrodp/message_ui/

Yes, definitely needs fixing, it's on my todo list and I had a few items I was stuck on. Will try again and create any issues. 👍

**Comment by RoySegall** [comment]
Yes. I added integration with the repo.

**Comment by mccrodp** [comment]
I see little red Xs, is this all good now @RoySegall ? (Failing, but running the tests ok)

**Comment by RoySegall** [comment]
It's definitely a start.
