### ISSUE TITLE
Add author as required field.

### ISSUE THREAD

**Issue by RoySegall** [RoySegall/message_ui#7]
When  creating the message we need the author as a required field.

**Comment by mccrodp** [comment]
I'm going to look at making this a requirement now. This would be helped in the UI by this PR: https://github.com/Gizra/message/pull/116 on message, which seems to be blocked due to a bug (tagged as release blocker): https://github.com/Gizra/message/issues/108

**Comment by mccrodp** [comment]
Created PR: https://github.com/RoySegall/message_ui/pull/12

**Comment by mccrodp** [comment]
Merged https://github.com/RoySegall/message_ui/pull/12
